name: fb_live_nlp
channels:
- defaults
dependencies:
- beautifulsoup4=4.6.0=py36_0
- jupyter=1.0.0=py36_3
- matplotlib=2.0.2=np113py36_0
- nltk=3.2.4=py36_0
- pandas=0.20.3=py36_0
- requests=2.14.2=py36_0
- scikit-learn=0.19.0=np113py36_0
- scipy=0.19.1=np113py36_0
- seaborn=0.8=py36_0
prefix: /Users/hugobowne/anaconda/envs/fb_live_nlp
